name: Ubuntu-noVNC-ngrok

on:
  workflow_dispatch:

jobs:
  ubuntu-vnc:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update and install GNOME + noVNC
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            ubuntu-desktop gnome-shell x11vnc novnc websockify xfce4-terminal wget unzip curl jq

      - name: Create VNC User with Random Password
        run: |
          PASSWORD=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 12)
          echo "VNC_PASS=$PASSWORD" >> $GITHUB_ENV
          
          sudo useradd -m -s /bin/bash vncuser
          echo "vncuser:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo vncuser

          mkdir -p /home/vncuser/.vnc
          echo "$PASSWORD" | x11vnc -storepasswd -f > /home/vncuser/.vnc/passwd
          sudo chown -R vncuser:vncuser /home/vncuser/.vnc
          chmod 600 /home/vncuser/.vnc/passwd

      - name: Start x11vnc + noVNC
        run: |
          # Chạy VNC server
          nohup sudo -u vncuser x11vnc -forever -usepw -create -display :0 > /tmp/x11vnc.log 2>&1 &
          
          # Chạy noVNC server trên port 6080
          nohup websockify --web=/usr/share/novnc/ 6080 localhost:5900 > /tmp/novnc.log 2>&1 &

      - name: Install ngrok
        run: |
          wget -qO ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/
          rm ngrok.zip
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start ngrok tunnel
        run: |
          nohup ngrok http 6080 > /tmp/ngrok.log 2>&1 &
          sleep 10
          NGROK_URL=$(curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV

      - name: Show Connection Info (Summary)
        run: |
          echo "### 🎉 Ubuntu GNOME noVNC Ready" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- 🌐 URL: $NGROK_URL/vnc.html" >> $GITHUB_STEP_SUMMARY
          echo "- 👤 Username: vncuser" >> $GITHUB_STEP_SUMMARY
          echo "- 🔑 Password: $VNC_PASS" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "⚠️ Nếu URL không mở được ngay, chờ vài giây rồi thử lại." >> $GITHUB_STEP_SUMMARY

      - name: Keep Alive
        run: |
          while true; do
            echo "[$(date)] Ubuntu GNOME via noVNC (ngrok) still running..."
            sleep 300
          done
