name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Core RDP Settings
        run: ./scripts/Configure-Rdp.ps1
        shell: pwsh

      - name: Disable Hyper-V and Prepare Emulator Support
        run: ./scripts/Prepare-EmulatorSupport.ps1
        shell: pwsh

      - name: Enable and Install Audio Support
        run: ./scripts/Enable-Audio.ps1
        shell: pwsh

      - name: Upgrade System Apps and Browsers
        run: ./scripts/Upgrade-SystemApps.ps1
        shell: pwsh

      - name: Install or Upgrade WSL
        run: ./scripts/Install-Wsl.ps1
        shell: pwsh

      - name: Create RDP User with Secure Password
        id: rdp_user_creds
        run: ./scripts/Create-RdpUser.ps1
        shell: pwsh

      - name: Install Tailscale
        run: ./scripts/Install-Tailscale.ps1
        shell: pwsh

      - name: Establish Tailscale Connection
        id: tailscale_connection
        run: ./scripts/Connect-Tailscale.ps1 -AuthKey "${{ secrets.TAILSCALE_AUTH_KEY }}" -RunId "${{ github.run_id }}"
        shell: pwsh

      - name: Verify RDP Accessibility
        run: ./scripts/Verify-Rdp.ps1 -TailscaleIp "${{ steps.tailscale_connection.outputs.tailscale_ip }}"
        shell: pwsh

      - name: Maintain Connection
        run: ./scripts/Maintain-Connection.ps1 -TailscaleIp "${{ steps.tailscale_connection.outputs.tailscale_ip }}" -RdpUser "${{ steps.rdp_user_creds.outputs.rdp_user }}" -RdpPassword "${{ steps.rdp_user_creds.outputs.rdp_password }}"
        shell: pwsh